// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD85ydxcnMREGV7WA2MjIWIK-kqgmwhQ8',
    appId: '1:156425404190:web:b29e8a726e32da0f78930f',
    messagingSenderId: '156425404190',
    projectId: 'proyecto-gradoinf',
    authDomain: 'proyecto-gradoinf.firebaseapp.com',
    storageBucket: 'proyecto-gradoinf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTkhKdaj9n_xlLv8YtepCSQpO2QE1CLZw',
    appId: '1:156425404190:android:7f6ea65e83e83e8c78930f',
    messagingSenderId: '156425404190',
    projectId: 'proyecto-gradoinf',
    storageBucket: 'proyecto-gradoinf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADth9aXstcNXGmR8FTKCLmKidZR9d57es',
    appId: '1:156425404190:ios:39974ebdf250e4f478930f',
    messagingSenderId: '156425404190',
    projectId: 'proyecto-gradoinf',
    storageBucket: 'proyecto-gradoinf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAppedu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADth9aXstcNXGmR8FTKCLmKidZR9d57es',
    appId: '1:156425404190:ios:39974ebdf250e4f478930f',
    messagingSenderId: '156425404190',
    projectId: 'proyecto-gradoinf',
    storageBucket: 'proyecto-gradoinf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationAppedu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD85ydxcnMREGV7WA2MjIWIK-kqgmwhQ8',
    appId: '1:156425404190:web:661cc8cd0d3ef99f78930f',
    messagingSenderId: '156425404190',
    projectId: 'proyecto-gradoinf',
    authDomain: 'proyecto-gradoinf.firebaseapp.com',
    storageBucket: 'proyecto-gradoinf.firebasestorage.app',
  );

}